version: 2
jobs:
    build:
        working_directory: /go/src/github.com/cactus/go-camo
        docker:
            - image: circleci/golang:1
        steps:
          - checkout
          - run: make test
