name: unit-tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    strategy:
      matrix:
        goVer: [1.13]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}
        id: go

      - name: Src Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make build

      - name: Check
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          go get github.com/securego/gosec/cmd/gosec
          hash -r
          make check

      - name: Tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test
