name: unit-tests
on:
  push:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go_version: [1.12, 1.13]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Go setup ${{ matrix.go_version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Tests
      run: make test
      env:
        GOPROXY: "https://proxy.golang.org"
